config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "restaurants#index"
  resources :restaurants do
    resources :reviews
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :delete_all
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :restaurants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user_edit, only:[:edit, :update]
  before_action :correct_user_delete, only:[:destroy]

  def index
    @restaurants = Restaurant.all
    @notice = "Please sign up or sign in to add, update or delete a restaurant"
  end
  def show
    @restaurant = Restaurant.find(params[:id])
    @notice = "Please sign up or sign in to add a review"
  end

  def new
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to @restaurant, {notice:"A new restaurant added"}
  end

  def update
    @restaurant = Restaurant.find(params[:id])
   
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, {notice: "updated successfully"}
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path, {notice: "A restaurant deleted"}
  end

  def correct_user_edit
    @restaurant = current_user.restaurants.find_by(id: params[:id])
    redirect_to restaurants_path, notice: "You cannot edit this restaurant" if @restaurant.nil?
  end

  def correct_user_delete
    @restaurant = current_user.restaurants.find_by(id: params[:id])
    redirect_to restaurants_path, notice: "You cannot delete this restaurant" if @restaurant.nil?
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :cuisine, :image_url, :description, :user_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.create(review_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@restaurant)
  end


  private
  def review_params
    params.require(:review).permit(:person, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show mt-3" role="alert">
  <%= notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>Restaurants Review</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "welcome/header"%>

    <% if notice%>
      <%= render "layouts/alerts"%>
    <% end%>

    <%= yield %>

    <%= render "welcome/footer"%>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1 class="m-3">Edit the restaurant</h1>

<div style="margin-bottom:80px;">
<%= form_with(model: @restaurant, local: true) do |form|%>

<div>
    <%= form.label :name, class:"h4 m-3" %><br>
    <%= form.text_field :name, class:"form-control m-3 w-50" %>
</div>

<div>
    <%= form.label :address, class:"h4 m-3" %><br>
    <%= form.text_field :address, class:"form-control m-3 w-50" %>
</div>
<div>
    <%= form.label :cuisine, class:"h4 m-3" %><br>
    <%= form.text_field :cuisine, class:"form-control m-3 w-50" %>
</div>
<div>
    <%= form.label :image_url, class:"h4 m-3" %><br>
    <%= form.text_field :image_url, class:"form-control m-3 w-50" %>
</div>
<div>
    <%= form.label :description, class:"h4 m-3" %><br>
    <%= form.text_field :description, class:"form-control m-3 w-50" %>
</div>

 <p>
    <%= form.submit class:"btn btn-primary m-3" %>
  </p>

  <%= link_to "back", restaurants_path, class:"btn btn-secondary m-3"%>


<% end%>
</div>

app/views/restaurants/index.html.erb
<% if user_signed_in?%>
<div><%= link_to "Add a restaurant", new_restaurant_path, class:"btn btn-secondary m-3"%></div>
<% else%>
 <div class="alert alert-warning alert-dismissible fade show mt-3" role="alert">
  <%= @notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
  </button>
 </div>
  <%= link_to "Sign Up", new_restaurant_path, class:"btn btn-primary m-2"%>
  <%= link_to "Sign In", new_user_session_path, class:"btn btn-secondary m-2"%>
<% end %>

<div class="d-flex flex-row bd-highlight mb-3 flex-wrap justify-content-center">
<% @restaurants.each do |restaurant|%>


    <div class="card" style="width: 25rem; margin:50px;">
      <img src=<%= restaurant.image_url%> class="card-img-top" alt="..." height="250px">
      <div class="card-body">
        <h5 class="card-title"><%= restaurant.name%></h5>
        <p class="card-text">Type of cuisine:<span class="badge bg-warning text-dark m-2"><%= restaurant.cuisine%></span></p>
        <div class="d-flex flex-row">
            <div><%= link_to "See detail", restaurant_path(restaurant), class:"btn btn-secondary m-1"%></div>
            <div><%= link_to "Make change", edit_restaurant_path(restaurant), class:"btn btn-warning m-1"%></div>
            <div><%= link_to "Delete", restaurant_path(restaurant), method: :delete, data:{confirm: "Are you sure?"}, class:"btn btn-danger m-1"%></div>   
        </div>
      </div>
    </div>


<% end %>
</div>

app/views/restaurants/new.html.erb
<h1 class="m-3">Add a new restaurant</h1>

<%= form_with scope: :restaurant, url: restaurants_path, local:true do |form|%>

<div>
    <%= form.text_field :name, class:"form-control m-2 m-3 w-50", placeholder:"Restaurant name" %>
</div>

<div>

    <%= form.text_field :address, class:"form-control m-3 w-50", placeholder:"Restaurant address" %>
</div>
<div>
    <%= form.text_field :cuisine, class:"form-control m-3 w-50", placeholder:"What Cuisine"  %>
</div>
<div>
    <%= form.text_field :image_url, class:"form-control m-3 w-50", placeholder:"Please provide a image url"  %>
</div>
<div>
    <%= form.text_field :description, class:"form-control m-3 w-50", placeholder:"Give a description"  %>
</div>
<div>
    <%= form.number_field :user_id, id: :restaurant_user_id, class:"form-control m-2", value: current_user.id, type: :hidden  %>
</div>



 <p>
    <%= form.submit class:"btn btn-primary m-3"%>
  </p>

  <%= link_to "back", :back, class:"btn btn-secondary m-3"%>


<% end%>

app/views/restaurants/show.html.erb
<div class="d-flex flex-row m-5">
    <div class="restaurant">
      <h1 class="m-2">
        <%= @restaurant.name %>
      </h1>
      
      <h2 class="m-2">
        <strong>Located in</strong>
        <%= @restaurant.address %>
      </h2>
      <h3 class="m-2">
        <span class="badge bg-warning text-dark m-2"><%= @restaurant.cuisine %></span>
      </h3>

      <p>
        <img src=<%= @restaurant.image_url %> alt="restaurant" width="500" >
      </p>

      <p>
        <div><strong>Description:</strong></div>
        <div style="border: 1px solid grey; max-width:auto; padding:10px; border-radius:15px; margin-top:15px"><%= @restaurant.description %></div>
      </p>

      <%= link_to "Back", restaurants_path, class:"btn btn-primary m-2"%>
      <%= link_to "Edit information", edit_restaurant_path(@restaurant), class:"btn btn-secondary m-2"%>
    </div>

  <div class="review" style="margin-left:200px">
    
    <div class="m-3">
      <% if @restaurant.reviews.any? %>
        <button class="btn btn-light fs-3 fw-bold">All reviews:
        <span class="badge bg-primary" style="vertical-align: top;"><%= @restaurant.reviews.length%></span>
        </button>
      <% end%>
        <% @restaurant.reviews.each do |review|%>
          <div class="m-4" style="border:2px solid orange; width:500px; padding:10px; border-radius:15px;">
            <h4><%= review.person %>:</h4>
            <%= review.body %>
              <% if current_user and current_user.id == @restaurant.user_id%>
              <p>
                <%= link_to "delete", [review.restaurant, review], method: :delete, data:{confirm: "Are you sure?"}, class:"btn btn-danger btn-sm mt-4"%>
              </p>
            <% end%>
          </div>
        <% end%>

        
    <% if user_signed_in?%>
    <h1>Add a review:</h1>

    <%= form_with model: [ @restaurant, @restaurant.reviews.build ] do |form| %>
      <p>
        <%= form.text_field :person, placeholder:"You are:", class:"form-control mt-3", value:current_user.email %>
      </p>
      <p>
        <%= form.text_area :body, placeholder:"How's this restaurant", class:"form-control"%>
      </p>
      <p>
        <%= form.submit class:"btn btn-primary" %>
      </p>

        
    <% end%>
    <% else%>
        <div class="alert alert-warning alert-dismissible fade show mt-3" role="alert">
      <%= @notice%>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
      </button>
    </div>
    <%= link_to "Sign Up", new_restaurant_path, class:"btn btn-primary"%>
    <%= link_to "Sign In", new_user_session_path, class:"btn btn-secondary"%>
    <% end%>
  </div>

</div>

app/views/welcome/_footer.html.erb
<footer class="bg-light text-center text-lg-start fixed-bottom">
  <!-- Copyright -->
  <div class="text-center p-3 fs-5 fw-bold" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2021 Copyright:
    <a class="text-dark" style="text-decoration:none;" href="https://jeffrey-website.herokuapp.com/" target="_blank">Jeffrey Shao</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/welcome/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Restaurant Reviews", restaurants_path, class:"navbar-brand fs-2" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-1 mb-lg-0">

      <% if user_signed_in?%>
        <li class="nav-item m-3 fs-4">
          <%= link_to "Add a Restaurant", new_restaurant_path, class:"nav-link" %>
        </li>

        <li class="nav-item m-3 fs-4">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

        <li class="nav-item m-3 fs-4">
          <%= link_to "Edit profile", edit_user_registration_path, class:"nav-link" %>
        </li>

        <div class="ms-auto m-3 fs-4">
          <li class="nav-item">
            <%= link_to "User Email: #{current_user.email}", edit_user_registration_path, class:"nav-link" %>
          </li>
        </div>

      <% else %>
        <li class="nav-item m-3 fs-4">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item m-3 fs-4">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
   
      <%end%>

        <%# <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li> %>
      </ul>

    </div>
  </div>
</nav>

app/views/welcome/index.html.erb
<h1>This is index page</h1>

<%= link_to "All the restaurants", controller: "restaurants"%>